---
- name: Create the libvirt_exporter group
  group:
    name: "{{ libvirt_exporter_system_group }}"
    state: present
    system: True
  when: libvirt_exporter_system_group != "root"
  tags:
    - libvirt_exporter

- name: Create the libvirt_exporter user
  user:
    name: "{{ libvirt_exporter_system_user }}"
    groups: "{{ libvirt_exporter_system_group }}"
    append: True
    shell: /usr/sbin/nologin
    system: True
    createhome: False
    home: /
  when: libvirt_exporter_system_user != "root"
  tags:
    - libvirt_exporter

- name: Ensure /usr/local/bin exists
  file:
    path: /usr/local/bin
    state: directory
    mode: 0755
  tags:
    - libvirt_exporter

- name: Download libvirt_exporter binary to local folder
  get_url:
    url: "https://github.com/patrickjahns/libvirt-prometheus-exporter/releases/download/{{ libvirt_exporter_version }}/libvirt_exporter-amd64"
    dest: "/usr/local/bin/libvirt_exporter"
    mode: 0755
  tags:
    - libvirt_exporter

- name: Write default
  notify:
    - Restart libvirt_exporter
  template:
    src: libvirt_exporter.default.j2
    dest: /etc/default/libvirt_exporter
  tags:
    - libvirt_exporter

- name: Prepare service
  notify:
    - Restart libvirt_exporter
  template:
    src: libvirt_exporter.service.j2
    dest: /etc/systemd/system/libvirt_exporter.service
  tags:
    - libvirt_exporter

- name: Ensure Libvirt Exporter is enabled on boot
  become: True
  systemd:
    daemon_reload: True
    name: libvirt_exporter
    enabled: True
    state: started
  tags:
    - libvirt_exporter
